### ISSUE TITLE
[UI/UX] Service Account Removal command - no message

### ISSUE THREAD

**Issue by adrianosela** [adrianosela/padl#132]
service account removal does not return error/ success message

```
18:20 $ padl project service-account remove --project demo-project --name deploybot2
```

**Comment by chrisneuf** [comment]
Is this done? looks like theres error messages to me in all the related functions

**Comment by adrianosela** [comment]
@chrisneuf its not done. run the commands. its possible that we are printing out whatever message sent by the server. but if that is "" then nothing gets printed

**Comment by adrianosela** [comment]
this is done
