### ISSUE TITLE
[NEED] change KMS key behavior

### ISSUE THREAD

**Issue by adrianosela** [adrianosela/padl#66]
Private keys should never be visible, we should instead provide api endpoints for encryption and decryption with a given key ID. (and remove the get private key call) This ensures nobody can take the 'team key' home.

**Comment by febg** [comment]
@adrianosela 
So the user will provide a key ID on the payload of the request, we will fetch the private key on the server and using the key ID?

What are we encrypting/ decrypting?

**Comment by adrianosela** [comment]
@febg the user will send a message to decrypt, and get it back decrypted.

**Comment by febg** [comment]
See [PR #68 ](https://github.com/adrianosela/padl/pull/68)
