### ISSUE TITLE
[NEED] JWT Based Deploy Keys

### ISSUE THREAD

**Issue by adrianosela** [adrianosela/padl#85]
we need to keep a map of `deployKeyName:deployKeyID` in our `Project` struct.

* Create new:
make a jwt for the project, with a jwt ID in it
save the jwt ID in the project's deploy keys map (name:id)

* Delete
just remove the named key from the map in the project object

Note: Our decryption request endpoint must be able to handle both user JWTs and these jwts.

**Comment by chrisneuf** [comment]
How Deploy Keys work (in the mind of Chris)

A registered User (with owner privileges) Logs in then

./padl project generateDeployKey —name ${project_name}

	What happens:
		client generates a RSA key pair 

		sends the public key to the server, the server then stores the public key in the 
                 DeployKeys map


Logging in with a deploy Key
	
Padl login --key ${path to private key} —name ${project_name}
	
	What happens:
		
	        The client signs the name of the project with the private key and sends a message to the 
                server that looks like this
		
                   { 
                     project name: ${name_passed_into_the_client}, 
                    secret: ${project_name_signed_with_private_key}
                }


	        the server gets the project from the name and checks if any of the deploy keys in the 
                project can decode the secret, if one decode matches the name of the project 
                authentication is successful and the server authenticates the client with a jwt that has 
                read only privilege

From here regular functions can be used to load a secret into the env

**Comment by adrianosela** [comment]
there will be no RSA keys involved with "deploy-keys". Padl deploy keys will be never-expiring JSON web tokens with a scope (the `aud` claim) different than our regular api scoped tokens. @chrisneuf

**Comment by adrianosela** [comment]
this way, the back end only has to keep track of a "jwt id" in our Project objects in db, instead of a whole separate RSA Key. We trust the signature on the JWT's we emit. @chrisneuf

**Comment by chrisneuf** [comment]
so what does the padl client login with to get the secrets

**Comment by adrianosela** [comment]
and the way they work is

- you log in
- padl project generate-deploy-key
>> spits out a JWT, which you can put on your automated processes.

@chrisneuf 
deploy key users (service accounts) never log in. The non-expiring, differently-scoped jwts can access the /key/decrypt endpoint ONLY (i.e. we need to extend our auth middleware to allow a different scope other than 'api' only in that endpoint, and only if the requested project contains the signed JWT's ID as one of its deploy-keys)

**Comment by chrisneuf** [comment]
So what does the client do then

assume I have a project running on a service and I need an API key thats so stored in padl.
I generate a deploy key and in return I get a jwt token.

I then go to the service machine that has my application and a new version of padl installed.

in my build script I then run: 
./padl service --jwt=${jwt_I_generated_earlier_on_a_diff_machine}
./padl project getSecret=API_KEY
this then loads the key to my env variable where my application can get it.

Is this correct?

**Comment by adrianosela** [comment]
```padl config set --url https://padl.adrianosela.com --token ${jwt_I_generated_earlier_on_a_diff_machine}```

then just the usual ```padl kms decrypt --id ${project_key_id} --secret ${secret}``` to decrypt a single secret. But to decrypt the padlfile, the client will pick up the token you set in the config command. (which still doesnt have a token flag btw) @chrisneuf

**Comment by adrianosela** [comment]
note that these token should only work for the particular decrypt endpoint

**Comment by chrisneuf** [comment]
so the padlfile also needs to be on the service machine, I guess we assume its in the project code?

**Comment by adrianosela** [comment]
yes sir, exaclty

**Comment by adrianosela** [comment]
we just need the creation command to spit an RSA private key and for the server to accept a pub, similar to user creation. @febg
